const { JSDOM } = require("jsdom");
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
let pass = 0, fail = 0;
const ok = (cond, msg) => { cond ? pass++ : fail++; console.log(`  ${cond ? "✓" : "✗ FAIL"} ${msg}`); };
const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8").replace('<script src="app.js"></script>', "");
const app = fs.readFileSync(path.join(ROOT, "app.js"), "utf8");
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://nevergiveup0618.github.io/learning/", pretendToBeVisual: true });
const { window: w } = dom;
Object.defineProperty(w.navigator, "serviceWorker", { value: null, configurable: true });
w.localStorage.setItem("sharedWallet_v1", JSON.stringify({ coins: 321, tickets: 7 }));
const today = new Date(), key = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`;
w.localStorage.setItem("magicEnglish_v1", JSON.stringify({ daily: { date:key,t1:true,t2:true,t3:false,t4:false } }));
w.localStorage.setItem("treasureWriting_v1", JSON.stringify({ daily: { date:key,quests:1,ideas:1,gems:1 } }));
w.eval(app);
const $ = s => w.document.querySelector(s);

console.log("学习大厅真实 DOM 测试");
ok($("#englishPortal").href === "https://nevergiveup0618.github.io/English/?v=39", "英语入口指向当前缓存版本");
ok($("#chinesePortal").href === "https://nevergiveup0618.github.io/Chinese/?v=32", "语文入口指向当前缓存版本");
$("#englishPortal").addEventListener("click", e => e.preventDefault(), {once:true});
$("#englishPortal").dispatchEvent(new w.MouseEvent("click", {bubbles:true,cancelable:true}));
ok($("#openingMask").classList.contains("on") && $("#openingText").textContent.includes("英语"), "★ 点击入口立即显示正在打开，不再像没点中");
ok(!!$(".baibai") && $(".baibai").getAttribute("src").includes("baibai-base.png"), "语文入口使用按实物照片重建的白白母版");
ok($("#coins").textContent === "321" && $("#tickets").textContent === "7", "只读展示 sharedWallet_v1 钱包");
ok($("#englishToday").textContent.includes("2 颗星"), "把英语进度表达成发现星星，不催任务");
ok($("#chineseToday").textContent.includes("宝物都找到啦"), "把语文完成度表达成找到宝物");
ok($("#englishProgress").style.width === "50%", "英语进度条正确");
ok($("#chineseProgress").style.width === "100%", "语文进度条正确");
ok($("#chineseAction").textContent.includes("探险护照"), "完成后给出有吸引力的返回文案");

w.localStorage.setItem("sharedWallet_v1", "损坏的存档");
w.localStorage.removeItem("magicEnglish_v1");
w.localStorage.removeItem("treasureWriting_v1");
w.learningHub.paint();
ok($("#coins").textContent === "0" && $("#englishToday").textContent.includes("等你来玩"), "缺失或损坏存档时轻松邀请，不白屏");
ok(!app.includes("setItem("), "导航页不写入两边的学习存档");
ok(fs.readFileSync(path.join(ROOT,"sw.js"),"utf8").includes("learning-planet-v7"), "缓存号已升级");
ok(fs.readFileSync(path.join(ROOT,"sw.js"),"utf8").includes('fallback || fresh'), "★ 慢网络优先显示缓存页并在后台更新");
ok(!w.document.body.textContent.includes("辛苦") && !w.document.body.textContent.includes("未完成"), "★ 导航页不使用制造压力的文案");

console.log(`\n结果: ${pass} 通过, ${fail} 失败`);
if (fail) process.exit(1);
