const { JSDOM } = require("jsdom");
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
let pass = 0, fail = 0;
const ok = (cond, msg) => { cond ? pass++ : fail++; console.log(`  ${cond ? "✓" : "✗ FAIL"} ${msg}`); };
const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8").replace('<script src="app.js"></script>', "");
const app = fs.readFileSync(path.join(ROOT, "app.js"), "utf8");
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://nevergiveup0618.github.io/learning/", pretendToBeVisual: true });
const { window: w } = dom;
Object.defineProperty(w.navigator, "serviceWorker", { value: null, configurable: true });
w.localStorage.setItem("sharedWallet_v1", JSON.stringify({ coins: 321, tickets: 7 }));
const today = new Date(), key = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`;
w.localStorage.setItem("magicEnglish_v1", JSON.stringify({ daily: { date:key,t1:true,t2:true,t3:false,t4:false } }));
w.localStorage.setItem("treasureWriting_v1", JSON.stringify({ daily: { date:key,quests:1,ideas:1,gems:1 } }));
w.localStorage.setItem("mathQuest_v1", JSON.stringify({ daily: { date:key, correct:5 }, wonders: { egypt:true, greece:true } }));
w.localStorage.setItem("sharedLearningJourney_v1",JSON.stringify([{subject:"en",screen:"study",day:key,seconds:180,at:Date.now()},{subject:"cn",screen:"reader",day:key,seconds:240,at:Date.now()},{subject:"ma",screen:"challenge",day:key,seconds:8,at:Date.now()}]));
w.eval(app);
const $ = s => w.document.querySelector(s);

console.log("学习大厅真实 DOM 测试");
ok($("#englishPortal").href === "https://nevergiveup0618.github.io/English/?v=66", "英语入口指向当前缓存版本");
ok($("#chinesePortal").href === "https://nevergiveup0618.github.io/Chinese/?v=44", "语文入口指向当前缓存版本");
$("#englishPortal").addEventListener("click", e => e.preventDefault(), {once:true});
$("#englishPortal").dispatchEvent(new w.MouseEvent("click", {bubbles:true,cancelable:true}));
ok($("#openingMask").classList.contains("on") && $("#openingText").textContent.includes("英语"), "★ 点击入口立即显示正在打开，不再像没点中");
ok(!!$(".baibai") && $(".baibai").getAttribute("src").includes("baibai-base.png"), "语文入口使用按实物照片重建的白白母版");
ok($("#coins").textContent === "321" && $("#tickets").textContent === "7", "只读展示 sharedWallet_v1 钱包");
ok($("#englishToday").textContent.includes("2 颗星"), "把英语进度表达成发现星星，不催任务");
ok($("#chineseToday").textContent.includes("宝物都找到啦"), "把语文完成度表达成找到宝物");
ok($("#englishProgress").style.width === "50%", "英语进度条正确");
ok($("#chineseProgress").style.width === "100%", "语文进度条正确");
ok($("#chineseAction").textContent.includes("探险护照"), "完成后给出有吸引力的返回文案");
ok($("#mathPortal").href === "https://nevergiveup0618.github.io/Math/?v=15", "数学入口指向数学奇境当前缓存版本");
ok($("#mathToday").textContent.includes("做对 5 题"), "数学显示今天做对题数（不设打卡）");
ok($("#mathAction").textContent.includes("继续穿越数学史"), "已收集奇观时给出继续文案");
ok(!!$(".pyramid") && $(".pyramid").getAttribute("aria-label") === "金色金字塔", "数学入口使用金字塔主题形象");
ok(parseFloat($("#mathProgress").style.width) > 22 && parseFloat($("#mathProgress").style.width) < 23, "数学进度按已收集奇观 2/9 计算");
$("#parentEntry").click();
ok($("#parentOverlay").classList.contains("on") && $("#parentPin"), "导航页打开统一家长中心且输入框不自动聚焦");
$("#parentPin").value="223826";$("#parentGo").click();
ok($("#parentBody").textContent.includes("英语") && $("#parentBody").textContent.includes("语文") && $("#parentBody").textContent.includes("数学"), "统一后台同页汇总三科");
ok($("#parentBody").textContent.includes("保存报告图片") && $("#parentBody").textContent.includes("共享钱包"), "统一后台支持图片报告和钱包管理");
ok($("#parentBody").textContent.includes("真实使用观察") && $("#parentBody").textContent.includes("快速退出"), "统一后台展示本机使用路径与退出观察");
ok($("#parentBody").textContent.includes("学单词") && $("#parentBody").textContent.includes("阅读答题") && $("#parentBody").textContent.includes("思维挑战"),"三科使用路径会翻译成家长看得懂的模块名称");
ok($("#parentBody").textContent.includes("内容与运行健康") && $("#parentBody").textContent.includes("长列表延迟渲染"), "统一后台展示内容自检和慢设备优化状态");
ok($("#downloadBackup") && $("#copyBackup") && $("#openRestore"), "统一后台可保存、复制和恢复三科总备份");
ok(w.document.querySelectorAll("[data-design-minutes]").length===4 && $("#parentBody").textContent.includes("设计工坊娱乐时间"), "统一家长后台显示5/10/20/30分钟选项");
w.document.querySelector("[data-design-minutes='10']").click();
ok(JSON.parse(w.localStorage.getItem("magicEnglish_v1")).designMinutes===10, "统一家长后台修改英语工坊时间并保存");
$("#openRestore").click();ok(!$("#restoreBox").hidden && w.document.activeElement!==$("#restoreCode"), "恢复区按需展开且不自动弹出键盘");
const backup=w.learningHub.backupCode(w.learningHub.makeBackup());w.localStorage.setItem("sharedWallet_v1",JSON.stringify({coins:1,tickets:0}));
ok(w.learningHub.restoreBackup(backup) && JSON.parse(w.localStorage.getItem("sharedWallet_v1")).coins===321,"三科总备份通过校验后可完整恢复共享数据");
ok(!w.learningHub.restoreBackup(backup.slice(0,-4)+"xxxx"),"损坏或不完整的三科备份会被拒绝");

w.localStorage.setItem("sharedWallet_v1", "损坏的存档");
w.localStorage.removeItem("magicEnglish_v1");
w.localStorage.removeItem("treasureWriting_v1");
w.localStorage.removeItem("mathQuest_v1");
w.learningHub.paint();
ok($("#coins").textContent === "0" && $("#englishToday").textContent.includes("等你来玩"), "缺失或损坏存档时轻松邀请，不白屏");
ok($("#mathToday").textContent.includes("等你来探险"), "数学缺档时轻松邀请");
ok(!app.includes('setItem("treasureWriting_v1"') && !app.includes('setItem("mathQuest_v1"'), "导航页除家长明确设定的英语工坊时间外，不改写学习存档");
ok(fs.readFileSync(path.join(ROOT,"sw.js"),"utf8").includes("learning-planet-v17"), "缓存号已升级");
ok(fs.readFileSync(path.join(ROOT,"sw.js"),"utf8").includes('fallback || fresh'), "★ 慢网络优先显示缓存页并在后台更新");
ok(!w.document.body.textContent.includes("辛苦") && !w.document.body.textContent.includes("未完成"), "★ 导航页不使用制造压力的文案");

console.log(`\n结果: ${pass} 通过, ${fail} 失败`);
if (fail) process.exit(1);
